version: 2
jobs:
  install_dapptools:
    docker:
      - image: nixos/nix:2.3.6
    working_directory: ~/protocol
    steps:
      - run:
          name: Install DappTools
          command: |
            nix-env -i cachix git
            cachix use dapp
            nix-env -iA dapp hevm seth solc -f https://api.github.com/repos/dapphub/dapptools/tarball/hevm/0.41.0
            git clone https://github.com/dapphub/dapptools.git /dapptools
            cd /dapptools
            git reset --hard 351e523d88497b21a5f023f9a20782d5972f7218
            nix-env -iA hevm dapp solc seth -f /dapptools
      - save_cache:
          key: dapptools_351e52
          paths:
            - /nix
            - /dapptools
  build_and_test:
    working_directory: ~/protocol
    docker:
      - image: nixos/nix:2.3.6
      - image: trufflesuite/ganache-cli
        command: ganache-cli -f https://mainnet.infura.io/v3/58073b4a32df4105906c702f167b91d2 -d -e 10000000 --networkId 1 -l 90000000
    steps:
      - checkout
      - restore_cache:
          keys:
            - dapptools_351e52
      - run:
          name: build
          command: |
            nix-env -iA hevm dapp solc seth -f /dapptools
            dapp update
            dapp build
            DAPP_TEST_NUMBER=$(expr $(seth block-number) - 2) DAPP_TEST_TIMESTAMP=$(date +%s) DAPP_TEST_BALANCE_CREATE=10000000000000000000000000 dapp test --rpc-url http://localhost:8545 -v

workflows:
  version: 2
  build:
    jobs:
      - install_dapptools
      - build_and_test